### ISSUE TITLE
license

### ISSUE THREAD

**Issue by mprosperi** [danielhanchen/hyperlearn#10]
do you mind to pass to a MIT/BSD license instead of GPL?

**Comment by danielhanchen** [comment]
@mprosperi  Hey! Sorry I'm not very well versed with licensing. What's the difference?

**Comment by mprosperi** [comment]
softwares that use GPL licensed libraries must be distributed with their source code and this limits commercial use of your library. MIT/BSD don't give this limitation to users. Pandas, sklearn, numpy are all BSD licenced

**Comment by danielhanchen** [comment]
@mprosperi  Oh ok. I was thinking of transferring it to an Apache 2 license. What do you think?

**Comment by mprosperi** [comment]
I think it's ok

**Comment by danielhanchen** [comment]
Changed to APACHE 2! Sorry for the delay
