### ISSUE TITLE
New Documentation - ReadTheDocs !

### ISSUE THREAD

**Issue by danielhanchen** [danielhanchen/hyperlearn#12]
Hey! I started documentation @ https://hyperlearn.readthedocs.io/en/latest/index.html

**Comment by themightyoarfish** [comment]
Would be awesome if you could use Sphinx's autodoc to have documentation generated for each function and submodule.

**Comment by themightyoarfish** [comment]
It would be worth noting that the C extensions need to be built before the doc compiles properly. I also had to install `psutil` which wasn't listed in `requirements.txt`. Then `make`ing `html` actually succeeds in extracting the info from the docstrings.

I can make a PR unless you want to handle it yourself.

**Comment by danielhanchen** [comment]
@themightyoarfish Thanks for noticing that! Ye that's an issue I had to face as way. Just kept forgetting every time I uploaded to git, I need to remake the docs :) I'll do it today. Thanks! :)

**Comment by danielhanchen** [comment]
@themightyoarfish Hmmmm I tried to update ReadTheDocs.
Locally, it works. On their server, it says "No module named 'hyperlearn.cython.base'". etc etc.
I'll try fixing it again.

**Comment by danielhanchen** [comment]
Documentation has been fixed! https://hyperlearn.readthedocs.io/en/latest/source/hyperlearn.html
I will add more docstrings and clean some up today! :)
