### ISSUE TITLE
Cannot import hyperlearn subpackages

### ISSUE THREAD

**Issue by themightyoarfish** [danielhanchen/hyperlearn#15]
After `python setup.py install` I get 
```
ModuleNotFoundError: No module named 'hyperlearn.cython'
```
when trying to ``import hyperlearn.(random|linalg|…)``. What could the problem be?

**Comment by danielhanchen** [comment]
Will fix this and get back to you! Sorry!

**Comment by themightyoarfish** [comment]
It seems to relate to the library not being on `PYTHONPATH`.

**Comment by themightyoarfish** [comment]
I have occasionally succeeded in importing the cython modules when setting `PYTHONPATH` to the build directory, but I also had to start the interpreter in a specific subdir of the build directory. Otherwise it wouldn't work. I really don't understand this.

Anyway, it also seems that the c extensions simply don't get installed alongside the python files.

**Comment by themightyoarfish** [comment]
Update: It seems to work now when I set `USE_CYTHON=True` in `setup.py`.

… or maybe it doesn't. I can `import hyperlearn.linalg`, but running
`hyperlearn.linalg.svd(np.random.rand(100,100))` gives me a `RecursionError`.
