### ISSUE TITLE
Undefined function in `randomized.linalg.svd`

### ISSUE THREAD

**Issue by themightyoarfish** [danielhanchen/hyperlearn#17]
https://github.com/danielhanchen/hyperlearn/blob/a2af0ba0420be6a2f036c761e7ecae9f0e66c21a/hyperlearn/randomized/linalg.py#L299

The name `_min` is not defined. Seems like that existed in `hyperlearn_old/numba` but not the current one.

**Comment by danielhanchen** [comment]
Oh yep Sorry once again! I was actually focusing on wrapping LAPACK and BLAS in cython, so I kinda neglected the other parts! Will get back to this! Thanks for finding these silly errors!
If you want, maybe use hyperlearn_old first.
Copy paste the folder to the desktop or wherever, and import that instead. It should be stable.
