### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by hoangthienan95** [danielhanchen/hyperlearn#20]
Hi there,
Thanks for the package! It looks very cool and seems like you put alot of work into it. Kudos!!! Sadly I can't find installation instructions anywhere. Can you point me to them?
Thanks,

**Comment by danielhanchen** [comment]
Hey! Thanks! As of now, you'll have to git clone the repo, then run python setup.py.
I'm currently working on making HyperLearn pip installable, but will take a while

**Comment by hoangthienan95** [comment]
@danielhanchen thanks for the info! I installed it successfully using `setup.py`, but then I do `python numba_compile.py` and got the following error? Do you know what could cause this?

```bash
******* Now compiling Numba and LLVM code..... *******
******* This can be VERY SLOW. Please wait.... *******
Progress: |||||||||||||||Note that first time import of HyperLearn will be slow, since NUMBA code has to be compiled to machine code for optimization purposes.
Traceback (most recent call last):
  File "numba_compile.py", line 6, in <module>
    from hyperlearn.numba.funcs import *
ModuleNotFoundError: No module named 'hyperlearn.numba.funcs'; 'hyperlearn.numba' is not a package
```

**Comment by danielhanchen** [comment]
Hi @hoangthienan95 Sorry about that!
Currently, I'm fixing errors for HyperLearn.
I'm planning to release a stable version this week.
